// Hier kommt deine Epic Games Liste aus der Zwischenablage rein!
// Folge der Anleitung in ANLEITUNG_Epic_Update.md.
window.IMPORTED_EPIC_GAMES = [
    "112 Operator",
    "Ace-Paket",
    "Aimlabs",
    "Antstream Arcade",
    "Antstream – Epic Welcome Pack",
    "Arcade Paradise",
    "Arcadgeddon",
    "Astrea Six Sided Oracles",
    "Bear and Breakfast",
    "BioShock: The Collection",
    "Black Widow: Recharged",
    "Bus Simulator 21 Next Stop",
    "Castlevania Anniversary Collection",
    "Chivalry 2",
    "Cities: Skylines",
    "DEATH STRANDING",
    "Dakar Desert Rally",
    "Das Cobalt-Paket",
    "Dead Island 2",
    "Deceive Inc.",
    "Deliver Us Mars",
    "Eastern Exorcist",
    "Empyrion - Galactic Survival",
    "F.I.S.T.: Forged In Shadow Torch",
    "F1® Manager 2024",
    "Football Manager 2024",
    "Fortnite Battle Royale - Startpaket",
    "Fortnite Battle Royale – Flügelmann-Startpaket",
    "Frostlegenden-Paket",
    "Ghostrunner",
    "Ghostrunner 2",
    "Giftiges Retro-Set",
    "GigaBash",
    "Gipfelstürmer-Paket",
    "Happy Game",
    "Hell Let Loose",
    "Hidden Folks",
    "Hogwarts Legacy",
    "INDUSTRIA",
    "Idle Champions of the Forgotten Realms",
    "Islets",
    "Jotunnslayer: Hordes of Hel",
    "Jurassic World Evolution",
    "Jurassic World Evolution 2",
    "K5 Saison 4 – Battle Pass-Geschenkmarke",
    "LEGO® Star Wars™: The Skywalker Saga",
    "Legion TD 2",
    "Maid of Sker",
    "Marvel Pinball Collection 1",
    "Marvel's Guardians of the Galaxy",
    "Midnight Ghost Hunt",
    "Model Builder: Complete Edition",
    "Mortal Shell",
    "Off The Grid - Early Access",
    "Ogu und der geheime Wald",
    "Outliver: Tribulation",
    "Oxenfree",
    "Pinball FX",
    "Pixel Gun 3D",
    "Predecessor",
    "River City Girls",
    "Road Redemption",
    "Rocket League Sideswipe",
    "Rocket League®",
    "Rugrats: Adventures in Gameland",
    "STAR WARS™ Battlefront™ II: Celebration Edition",
    "STAR WARS™: Squadrons",
    "SUPER CRAZY RHYTHM CASTLE",
    "ScourgeBringer",
    "Sid Meier's Civilization® VI Platinum Edition",
    "Sniper Ghost Warrior Contracts",
    "Songs of Silence",
    "Soulstice",
    "Spelldrifter",
    "Styx: Master of Shadows",
    "Styx: Shards of Darkness - Deluxe Edition",
    "Super Meat Boy Forever",
    "Surviving the Aftermath",
    "The Operator",
    "The Outer Worlds: Spacer's Choice Edition",
    "Totally Reliable Delivery Service Standard Edition",
    "Trackmania Starter Access",
    "Two Point Hospital",
    "Universal Classics™ Pinball",
    "Unreal Engine 5",
    "VALORANT",
    "Wahre-Entdecker-Auftragspaket",
    "Wizard of Legend",
    "World War Z: Aftermath",
    "Wrath of the Elder Gods",
    "theHunter: Call of the Wild™"
];